spring:
  application:
    name: movie-consumer-feign-custom
server:
  port: 8050
eureka:
  client:
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
logging:
  level:
    com.zzh.cloud.feign.UserFeignCustomClient: DEBUG
