server:
  port: 8255
spring:
  application:
    name: config-server-encrypt
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chiva-Zhao/clouddemo_config
management:
  security:
    enabled: false
my:
  password: '{cipher}964a2b8b5298c508c5f59ec10cc5a01e6f825c239cfe239c4927a329513e9130'
