spring:
  application:
    name: movie-ribbon-without-eureka
server:
  port: 8040
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
ribbon:
  eureka:
    enabled: false
user-provider-reg:
  ribbon:
#    ≤‚ ‘“ª
#    listOfServers: localhost:7900
#    ≤‚ ‘∂˛
    listOfServers: localhost:7898,localhost:7899,localhost:7900
