server:
  port: 8265
spring:
  application:
    name: config-server-encrypt-rsa
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chiva-Zhao/clouddemo_config
#          username:    # 自己设置，这里就不做演示了
#          password:    # 自己设置，这里就不做演示了