spring:
  application:
    name: movie-consumer
server:
  port: 7901
user:
  userServicePath: http://localhost:7900/user/
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
