server:
  port: 8190
spring:
  application:
    name: simple-upload
  http:
      multipart:
        max-file-size: 20Mb      # Max file size£¬Ä¬ÈÏ1M
        max-request-size: 20Mb   # Max request size£¬Ä¬ÈÏ10M

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: INFO
    com.zzh.cloud: DEBUG
    com.netflix: debug
