server:
  port: 8190
spring:
  application:
    name: simple-upload
  http:
      multipart:
        max-file-size: 20Mb      # Max file size，默认1M
        max-request-size: 20Mb   # Max request size，默认10M

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
logging:
  level:
    root: INFO
    com.zzh.cloud: DEBUG
    com.netflix: debug
