spring:
  application:
    name: movie-consumer-ribbon
server:
  port: 8010
eureka:
  client:
    service-url:
      default-zone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}